apiVersion: v1
kind: PersistentVolume
metadata:
  name: be-local-pv
spec:
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: doris-be-storage
  local:
    path: /var/bigdata/servers/doris/data/be
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: be-pvc
  namespace: doris
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: doris-be-storage
  volumeName: be-local-pv