apiVersion: v1
kind: Pod
metadata:
  name: spark-shell-hadoop
  namespace: hadoop
spec:
  restartPolicy: Never
  containers:
  - name: spark-shell
    image: spark-shell-hive:3.5.3
    command: ["/opt/spark/bin/spark-shell"]
    env:
    - name: SPARK_CONF_DIR
      value: /opt/spark/conf
    - name: HADOOP_CONF_DIR
      value: /opt/spark/conf/hadoop
    - name: HADOOP_HIVE_CONF_DIR
      value: /opt/spark/conf/hadoop-hive
    volumeMounts:
      - name: hadoop-config-volume
        mountPath: /opt/spark/conf/hadoop
      - name: hadoop-hive-config-volume
        mountPath: /opt/spark/conf/hadoop-hive
      - name: spark-config-volume
        mountPath: /opt/spark/conf
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
  volumes:
    - name: hadoop-hive-config-volume
      configMap:
        name: hadoop-hadoop-hive
    - name: hadoop-config-volume
      configMap:
        name: hadoop-hadoop
    - name: spark-config-volume
      configMap:
        name: spark-shell-config
  